name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
        if: github.ref == 'refs/heads/master'
      - uses: docker/setup-buildx-action@v2
        if: github.ref == 'refs/heads/master'
      - name: Login to GHCR
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Build and push
        uses: docker/build-push-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/rasmus-saks/photon-docker:latest
